export const booksData = [
  {
    title: 'The Alchemist',
    slug: 'the-alchemist',
    price: 499.99,
    stock: 10,
    isbn: '978-3-16-148410-0',
    publishedDate: new Date('2024-01-01'),
    images: ['/images/the_alchemist.jpg'],
    description: 'A philosophical novel inspiring readers to follow their dreams.',
    rating: 4.6,
    numReviews: 12,
    banner: null,
    isFeatured: false,
  },
  {
    title: 'Harry Potter and the Sorcerer’s Stone',
    slug: 'harry-potter-sorcerer-stone',
    price: 899.99,
    stock: 15,
    isbn: '978-0-7475-3269-9',
    publishedDate: new Date('1997-06-26'),
    images: ['/images/harry_potter.jpg'],
    description: 'The first book in J.K. Rowling’s Harry Potter series.',
    rating: 4.6,
    numReviews: 12,
    banner: null,
    isFeatured: false,
  },
  {
    title: '1984',
    slug: '1984',
    price: 399.99,
    stock: 20,
    isbn: '978-0-452-28423-4',
    publishedDate: new Date('1949-06-08'),
    images: ['/images/1984.jpg'],
    description: 'A dystopian novel by George Orwell.',
    rating: 4.6,
    numReviews: 12,
    banner: null,
    isFeatured: false,
  },
  {
    title: 'Pride and Prejudice',
    slug: 'pride-and-prejudice',
    price: 299.99,
    stock: 25,
    isbn: '978-0-19-280238-5',
    publishedDate: new Date('1813-01-28'),
    images: ['/images/pride_prejudice.jpg'],
    description: 'A classic novel by Jane Austen.',
    rating: 4.6,
    numReviews: 12,
  },
  {
    title: 'The Great Gatsby',
    slug: 'the-great-gatsby',
    price: 349.99,
    stock: 30,
    isbn: '978-0-7432-7356-5',
    publishedDate: new Date('1925-04-10'),
    images: ['/images/great_gatsby.jpg'],
    description: 'A novel by F. Scott Fitzgerald set in the Jazz Age.',
    rating: 4.6,
    numReviews: 12,
  },
];

export default booksData;
